/*
 *
 * Copyright 2021-2023 NXP.
 *
 * NXP Confidential. This software is owned or controlled by NXP and may only be
 * used strictly in accordance with the applicable license terms. By expressly
 * accepting such terms or by downloading,installing, activating and/or
 * otherwise using the software, you are agreeing that you have read,and that
 * you agree to comply with and are bound by, such license terms. If you do not
 * agree to be bound by the applicable license terms, then you may not retain,
 * install, activate or otherwise use the software.
 *
 */

/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
/* !!! AUTO GENERATED FILE  !!!!!!!!!!!!!!!!!!!!! */
/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */

#pragma once

/* Options for selection of the demos : START */

/* Uncomment **ONE**, and comment out **rest** of them. */

//  #define UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER
//  #define UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE
//  #define UWBIOT_APP_BUILD__DEMO_BINDING
//  #define UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX
//  #define UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX
//  #define UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY
//  #define UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE
//  #define UWBIOT_APP_BUILD__DEMO_FL_INITIATOR
//  #define UWBIOT_APP_BUILD__DEMO_FL_RESPONDER
//  #define UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY
//  #define UWBIOT_APP_BUILD__DEMO_PNP
//  #define UWBIOT_APP_BUILD__DEMO_MCTT_PCTT
//  #define UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION
// #define UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT
// #define UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR
// #define UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER
// #define UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG
// #define UWBIOT_APP_BUILD__SE_VCOM
// #define UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER
// #define UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR
// #define UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR
// #define UWBIOT_APP_BUILD__DEMO_TEST_TX
// #define UWBIOT_APP_BUILD__DEMO_TEST_RX
// #define UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER
// #define UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE
// #define UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE

/* Options for selection of the demos : END */

/* Helper compile time check to safeguard wrong selection at compile time. */

/* clang-format off */
#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_BINDING)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_BINDING'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_PNP)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_PNP'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_BINDING)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_BINDING'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_PNP)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_PNP'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_PNP)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_PNP'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_BINDING) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_BINDING' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_PNP)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_PNP'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_RX' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_PNP)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_PNP'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_INBAND_DATA_TRANSFER_TX' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_PNP)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_PNP'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_FACTORY' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_PNP)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_PNP'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OTP_STORAGE_MAINLINE' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_PNP)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_PNP'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_PNP)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_PNP'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_PNP)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_PNP'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_FL_RESPONDER_IOT_CONCURRENCY' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_PNP) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_PNP' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_MCTT_PCTT) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_MCTT_PCTT' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_NEARBY_INTERACTION_CLIENT' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_INITIATOR' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_RESPONDER' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG) && defined(UWBIOT_APP_BUILD__SE_VCOM)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG' and 'UWBIOT_APP_BUILD__SE_VCOM'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_DLTDOA_TAG' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__SE_VCOM) && defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER)
#    error Can not define both 'UWBIOT_APP_BUILD__SE_VCOM' and 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER'
#endif

#if defined(UWBIOT_APP_BUILD__SE_VCOM) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__SE_VCOM' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__SE_VCOM) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__SE_VCOM' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__SE_VCOM) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__SE_VCOM' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__SE_VCOM) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__SE_VCOM' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__SE_VCOM) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__SE_VCOM' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__SE_VCOM) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__SE_VCOM' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__SE_VCOM) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__SE_VCOM' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_OWR_AOA_ADVERTISER' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_TEST_TX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_TEST_TX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_ULTDOA_SYNC_ANCHOR' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif
/*
#if defined(UWBIOT_APP_BUILD__DEMO_TEST_TX) && defined(UWBIOT_APP_BUILD__DEMO_TEST_RX)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_TEST_TX' and 'UWBIOT_APP_BUILD__DEMO_TEST_RX'
#endif
*/
#if defined(UWBIOT_APP_BUILD__DEMO_TEST_TX) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_TEST_TX' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_TEST_TX) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_TEST_TX' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_TEST_TX) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_TEST_TX' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_TEST_RX) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_TEST_RX' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_TEST_RX) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_TEST_RX' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_TEST_RX) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_TEST_RX' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLLER' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

#if defined(UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE) && defined(UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE)
#    error Can not define both 'UWBIOT_APP_BUILD__DEMO_HYBRID_RANGING_CONTROLEE' and 'UWBIOT_APP_BUILD__DEMO_CSA_CONTROLEE'
#endif

/* clang-format on */
